env:
  dev177
spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/SpringCloud_Sell?characterEncoding=utf-8&userSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: Long6617
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    port: 5672
    host: 192.168.242.131
    username: guest
    password: guest 
    stream:
      bindings:
        myMessage:
          group: order
          content-type: application/json

server:
  port: 8763

#hystrix的超时时间
# hystrix:
#   command:
#     default:
#       execution:
#         timeout:
#           enabled: true
#         isolation:
#           thread:
#             timeoutInMilliseconds: 30000
#ribbon的超时时间
# ribbon:
#   ReadTimeout: 30000
#   ConnectTimeout: 30000
