spring: 
  datasource:
    username: root
    password: Long6617
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.242.131
    username: guest
    password: guest
    port: 5672
server:
  port: 9080
