spring:
  application:
    name: user
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/SpringCloud_Sell?characterEncoding=utf-8&&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: Long6617
    driverClassName: com.mysql.jdbc.Driver
