spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/SpringCloud_Sell?characterEncoding=utf-8&&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: Long6617
    driverClassName: com.mysql.jdbc.Driver
  redis:
    host: 192.168.242.131
    port: 6379
